image = "art/textures/font/font.bmp"
tile_size = {x = 12, y = 12}

[Tiles]
# Upper case letters
A = {x = 0, y = 0}
B = {x = 1, y = 0}
C = {x = 2, y = 0}
D = {x = 3, y = 0}
E = {x = 4, y = 0}
F = {x = 5, y = 0}
G = {x = 6, y = 0}
H = {x = 7, y = 0}
I = {x = 8, y = 0}
J = {x = 9, y = 0}
K = {x = 10, y = 0}
L = {x = 11, y = 0}
M = {x = 12, y = 0}
N = {x = 13, y = 0}
O = {x = 14, y = 0}
P = {x = 15, y = 0}
Q = {x = 16, y = 0}
R = {x = 17, y = 0}
S = {x = 18, y = 0}
T = {x = 19, y = 0}
U = {x = 20, y = 0}
V = {x = 21, y = 0}
W = {x = 22, y = 0}
X = {x = 23, y = 0}
Y = {x = 24, y = 0}
Z = {x = 25, y = 0}

# Lower case letters
a = {x = 0, y = 1}
b = {x = 1, y = 1}
c = {x = 2, y = 1}
d = {x = 3, y = 1}
e = {x = 4, y = 1}
f = {x = 5, y = 1}
g = {x = 6, y = 1}
h = {x = 7, y = 1}
i = {x = 8, y = 1}
j = {x = 9, y = 1}
k = {x = 10, y = 1}
l = {x = 11, y = 1}
m = {x = 12, y = 1}
n = {x = 13, y = 1}
o = {x = 14, y = 1}
p = {x = 15, y = 1}
q = {x = 16, y = 1}
r = {x = 17, y = 1}
s = {x = 18, y = 1}
t = {x = 19, y = 1}
u = {x = 20, y = 1}
v = {x = 21, y = 1}
w = {x = 22, y = 1}
x = {x = 23, y = 1}
y = {x = 24, y = 1}
z = {x = 25, y = 1}

# Numbers
"0" = {x = 0, y = 2}
"1" = {x = 1, y = 2}
"2" = {x = 2, y = 2}
"3" = {x = 3, y = 2}
"4" = {x = 4, y = 2}
"5" = {x = 5, y = 2}
"6" = {x = 6, y = 2}
"7" = {x = 7, y = 2}
"8" = {x = 8, y = 2}
"9" = {x = 9, y = 2}

# Symbols
"?" = {x = 26, y = 0}
"(" = {x = 27, y = 0}
")" = {x = 28, y = 0}
"[" = {x = 29, y = 0}
"]" = {x = 30, y = 0}
"^" = {x = 31, y = 0}
"!" = {x = 26, y = 1}
"{" = {x = 27, y = 1}
"}" = {x = 28, y = 1}
"<" = {x = 29, y = 1}
">" = {x = 30, y = 1}
"+" = {x = 31, y = 1}
"-" = {x = 32, y = 1}
":" = {x = 10, y = 2}
"#" = {x = 11, y = 2}
"_" = {x = 12, y = 2}
"@" = {x = 13, y = 2}
"%" = {x = 14, y = 2}
"~" = {x = 15, y = 2}
"$" = {x = 16, y = 2}
"\"" = {x = 17, y = 2}
"'" = {x = 18, y = 2}
"&" = {x = 19, y = 2}
"*" = {x = 20, y = 2}
"=" = {x = 21, y = 2}
"`" = {x = 22, y = 2}
"|" = {x = 23, y = 2}
"/" = {x = 24, y = 2}
"\\" = {x = 25, y = 2}
"." = {x = 26, y = 2}
"," = {x = 27, y = 2}
";" = {x = 28, y = 2}
" " = {x = 29, y = 2}

# Box
"┌" = {x = 0, y = 3}
"│" = {x = 0, y = 4}
"└" = {x = 0, y = 5}
"─" = {x = 1, y = 3}
"┼" = {x = 1, y = 4}
"┐" = {x = 2, y = 3}
"┘" = {x = 2, y = 5}
"┬" = {x = 3, y = 3}
"├" = {x = 3, y = 4}
"┤" = {x = 2, y = 4}
"┴" = {x = 1, y = 5}
"╭" = {x = 9, y = 3}
"╮" = {x = 10, y = 3}
"╰" = {x = 9, y = 4}
"╯" = {x = 10, y = 4}

# Block
"░" = {x = 4, y = 3}
"▒" = {x = 4, y = 4}
"▓" = {x = 4, y = 5}
"█" = {x = 3, y = 5}
